# Generated by Django 5.2.3 on 2025-07-12 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="last_update",
            field=models.DateTimeField(
                auto_now=True, verbose_name="последнее обновление"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="last_update",
            field=models.DateTimeField(
                auto_now=True, verbose_name="последнее обновление"
            ),
        ),
    ]
